name: admiralui_flutter
description: The visual component library for Flutter
version: 0.0.1
homepage: https://github.com/admiral-team/admiralui-flutter.git

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  admiralui: ^0.0.1
  flutter:
    sdk: flutter
  golden_toolkit: ^0.13.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  recase: ^4.0.0
  xml: ^5.2.0

flutter:
  fonts:
    - family: AdmiralIcons
      fonts:
        - asset: lib/fonts/AdmiralIcons.ttf
    - family: sfProDisplay
      fonts:
        - asset: lib/fonts/SFProDisplay-Regular.otf
        - asset: lib/fonts/SFProDisplay-Medium.otf
        - asset: lib/fonts/SFProDisplay-Bold.otf
        - asset: lib/fonts/SFProDisplay-Semibold.otf
    - family: sfProText
      fonts:
        - asset: lib/fonts/SFProText-Medium.otf