import 'package:admiralui_flutter/admiralui_flutter.dart';
import 'package:flutter/material.dart';

class AdmiralIconsFlutterList {
  static const List<String> iconNames = <String>[
    'accept_outline',
    'accept_solid',
    'account_detail_outline',
    'account_detail_solid',
    'acuring_future_outline',
    'acuring_future_solid',
    'acuring_modern_outline',
    'acuring_modern_solid',
    'add_comment_outline',
    'add_comment_solid',
    'add_from_template_outline',
    'add_from_template_solid',
    'add_template_outline',
    'add_template_solid',
    'admin_outline',
    'admin_solid',
    'administrator_at_outline',
    'administrator_at_solid',
    'administrator_ht_outline',
    'administrator_ht_solid',
    'agreed_outline',
    'agreed_solid',
    'alert_outline',
    'alert_solid',
    'align_center_outline',
    'align_left_outline',
    'align_middle_outline',
    'align_right_outline',
    'align_top_outline',
    'amount_outline',
    'anchor_outline',
    'anchor_solid',
    'application_administrator_outline',
    'application_administrator_solid',
    'archive_outline',
    'archive_solid',
    'area_chart_outline',
    'area_chart_solid',
    'arrow_cross_outline',
    'arrow_cross_solid',
    'arrow_down_one_outline',
    'arrow_down_one_solid',
    'arrow_down_outline',
    'arrow_down_solid',
    'arrow_down_two_outline',
    'arrow_down_two_solid',
    'arrow_left_outline',
    'arrow_left_solid',
    'arrow_right_outline',
    'arrow_right_solid',
    'arrow_up_down_outline',
    'arrow_up_down_solid',
    'arrow_up_one_outline',
    'arrow_up_one_solid',
    'arrow_up_outline',
    'arrow_up_solid',
    'arrow_up_two_outline',
    'arrow_up_two_solid',
    'arrows_horizontal_outline',
    'arrows_horizontal_solid',
    'arrows_vertical_outline',
    'arrows_vertical_solid',
    'at_outline',
    'at_solid',
    'attach_file_outline',
    'attach_file_solid',
    'back_outline',
    'back_solid',
    'bank_outline',
    'bank_solid',
    'bar_chart__outline',
    'bar_chart_plus_outline',
    'bar_chart_plus_solid',
    'bar_chart_solid',
    'bar_code_outline',
    'bar_code_solid',
    'bg_color_outline',
    'bonus_outline',
    'bonus_ruble_outline',
    'bonus_ruble_solid',
    'bonus_solid',
    'book_outline',
    'book_solid',
    'border_bold_bottom_outline',
    'border_bold_left_outline',
    'border_bold_outter_outline',
    'border_bold_right_outline',
    'border_bold_top_outline',
    'border_bottom_outline',
    'border_clear_outline',
    'border_horizontal_outline',
    'border_inner_outline',
    'border_left_outline',
    'border_outer_outline',
    'border_right_outline',
    'border_style_outline',
    'border_top_outline',
    'border_vertical_outline',
    'branches_outline',
    'branches_solid',
    'broker_outline',
    'broker_solid',
    'bug_outline',
    'bug_solid',
    'burn_card_outline',
    'burn_card_solid',
    'burn_outline',
    'burn_solid',
    'bus_outline',
    'bus_solid',
    'calculate_outline',
    'calculate_solid',
    'calendar_ok_outline',
    'calendar_ok_solid',
    'calendar_outline',
    'calendar_solid',
    'calendar_update_outline',
    'calendar_update_solid',
    'camera_outline',
    'camera_remove_outline',
    'camera_remove_solid',
    'camera_solid',
    'cancel_megaphone_outline',
    'cancel_megaphone_solid',
    'car_outline',
    'car_solid',
    'card_outline',
    'card_solid',
    'card_t_outline',
    'card_t_solid',
    'card_tp_outline',
    'card_tp_solid',
    'cash_outline',
    'cash_solid',
    'cashbox_outline',
    'cashbox_solid',
    'catalog_outline',
    'catalog_solid',
    'cells_disconnect_outline',
    'cells_merge_outline',
    'chair_outline',
    'chair_solid',
    'change_field_outline',
    'chart_outline',
    'chart_solid',
    'chat_outline',
    'chat_solid',
    'check_outline',
    'check_solid',
    'chess_king_outline',
    'chess_king_solid',
    'chevron_down_outline',
    'chevron_down_solid',
    'chevron_left_outline',
    'chevron_left_solid',
    'chevron_right_outline',
    'chevron_right_solid',
    'chevron_up_outline',
    'chevron_up_solid',
    'chip_outline',
    'chip_solid',
    'clipboard_outline',
    'clipboard_solid',
    'clone_outline',
    'clone_solid',
    'close_circle_outline',
    'close_circle_solid',
    'close_fullscreen_outline',
    'close_fullscreen_solid',
    'close_outline',
    'close_solid',
    'cloud_done_outline',
    'cloud_done_solid',
    'cloud_not_available_outline',
    'cloud_not_available_solid',
    'cloud_outline',
    'cloud_solid',
    'cloud_upload_outline',
    'cloud_upload_solid',
    'color_outline',
    'color_solid',
    'column_delete_outline',
    'column_insert_after_outline',
    'column_insert_before_outline',
    'columns_outline',
    'comment_outline',
    'comment_solid',
    'commits_outline',
    'commits_solid',
    'compare_outline',
    'compare_solid',
    'component_outline',
    'component_solid',
    'component_template_outline',
    'component_template_solid',
    'copy_outline',
    'copy_solid',
    'create_branches_outline',
    'create_branches_solid',
    'create_fork_outline',
    'create_fork_solid',
    'create_pull_request_outline',
    'create_pull_request_solid',
    'credit_card_outline',
    'credit_card_solid',
    'credit_outline',
    'credit_solid',
    'cube_outline',
    'cube_solid',
    'cut_outline',
    'cut_solid',
    'cvv_outline',
    'cvv_solid',
    'danger_outline',
    'danger_solid',
    'dark_mode_outline',
    'dark_mode_solid',
    'debit_card_outline',
    'debit_card_solid',
    'delete_docs_outline',
    'delete_docs_solid',
    'delete_document_outline',
    'delete_document_solid',
    'delete_outline',
    'delete_solid',
    'delete_style_outline',
    'delete_table_outline',
    'delivery_outline',
    'delivery_solid',
    'deposit_outline',
    'deposit_solid',
    'description_outline',
    'description_solid',
    'desktop_outline',
    'desktop_solid',
    'developer_outline',
    'developer_solid',
    'devops_engineer_outline',
    'devops_engineer_solid',
    'diamond_outline',
    'diamond_solid',
    'digitalmoney_outline',
    'digitalmoney_solid',
    'doc_attention_outline',
    'doc_attention_solid',
    'doc_export_outline',
    'doc_export_solid',
    'doc_finished_outline',
    'doc_finished_solid',
    'doc_ok_outline',
    'doc_ok_solid',
    'doc_operations_outline',
    'doc_operations_solid',
    'doc_processing_outline',
    'doc_processing_solid',
    'doc_regenerate_outline',
    'doc_regenerate_solid',
    'doc_settings_outline',
    'doc_settings_solid',
    'doc_sign_outline',
    'doc_sign_solid',
    'doc_sign_verify_outline',
    'doc_sign_verify_solid',
    'doc_view_outline',
    'doc_view_solid',
    'docs_outline',
    'docs_solid',
    'document_add_outline',
    'document_add_solid',
    'dots_menu_outline',
    'dots_menu_solid',
    'double_arrow_down_outline',
    'double_arrow_down_solid',
    'double_arrow_left_outline',
    'double_arrow_left_solid',
    'double_arrow_right_outline',
    'double_arrow_right_solid',
    'double_arrow_up_outline',
    'double_arrow_up_solid',
    'download_outline',
    'download_solid',
    'drag_outline',
    'drag_solid',
    'duplicate_outline',
    'duplicate_solid',
    'edit_outline',
    'edit_solid',
    'elderly_outline',
    'elderly_solid',
    'element_fixed_outline',
    'element_grow_horizontally_outline',
    'element_grow_vertically_outline',
    'email_outline',
    'email_read_outline',
    'email_read_solid',
    'email_solid',
    'emoji_neutal_outline',
    'emoji_neutral_solid',
    'emoji_sad_outline',
    'emoji_sad_solid',
    'emoji_smile_outline',
    'emoji_smile_solid',
    'envelope_outline',
    'envelope_solid',
    'equally_outline',
    'equally_solid',
    'eraser_outline',
    'eraser_solid',
    'error_outline',
    'error_solid',
    'error_triangle_outline',
    'error_triangle_solid',
    'eur_outline',
    'eur_solid',
    'exit_outline',
    'exit_solid',
    'export_outline',
    'export_solid',
    'eye_close_outline',
    'eye_off_outline',
    'eye_off_solid',
    'eye_outline',
    'eye_solid',
    'eyedropper_outline',
    'eyedropper_solid',
    'faceid_outline',
    'faceid_solid',
    'file_csv_outline',
    'file_csv_solid',
    'file_currency_outline',
    'file_currency_solid',
    'file_doc_outline',
    'file_doc_solid',
    'file_jpg_outline',
    'file_jpg_solid',
    'file_pdf_outline',
    'file_pdf_solid',
    'file_ppt_outline',
    'file_ppt_solid',
    'file_sng_outline',
    'file_sng_solid',
    'file_tif_outline',
    'file_tif_solid',
    'file_tiff_outline',
    'file_tiff_solid',
    'file_txt_outline',
    'file_txt_solid',
    'file_word_outline',
    'file_word_solid',
    'file_xls_outline',
    'file_xls_solid',
    'file_xml_outline',
    'file_xml_solid',
    'filter_outline',
    'filter_solid',
    'finance_outline',
    'finance_solid',
    'fingerprint_outline',
    'fingerprint_solid',
    'flag_outline',
    'flag_solid',
    'flash_light_outline',
    'flash_light_solid',
    'folder_outline',
    'folder_solid',
    'font_style_outline',
    'forks_outline',
    'forks_solid',
    'format_align_justify_outline',
    'format_paint_outline',
    'format_paint_solid',
    'gallery_outline',
    'gallery_solid',
    'game_outline',
    'game_solid',
    'gantt_chart_outline',
    'gantt_chart_solid',
    'gbp_outline',
    'gbp_solid',
    'get_cash_outline',
    'get_cash_solid',
    'globe_outline',
    'globe_solid',
    'gold_outline',
    'gold_solid',
    'government_outline',
    'government_solid',
    'gps_outline',
    'gps_solid',
    'grid_outline',
    'grid_solid',
    'group_objects_outline',
    'group_objects_solid',
    'headset_outline',
    'headset_solid',
    'heart_outline',
    'heart_solid',
    'help_outline',
    'help_solid',
    'hide_left_panel_outline',
    'hide_right_panel_outline',
    'hierarchy_outline',
    'hierarchy_solid',
    'home_autocredit_outline',
    'home_autocredit_solid',
    'home_outline',
    'home_solid',
    'hook_outline',
    'hook_solid',
    'huge_procent_outline',
    'huge_procent_solid',
    'icons_outline',
    'icons_solid',
    'idea_outline',
    'idea_solid',
    'iis_outline',
    'iis_solid',
    'import_outline',
    'import_solid',
    'inbox_outline',
    'inbox_solid',
    'incognito_outline',
    'incognito_solid',
    'indent_decrease_outline',
    'indent_increase_outline',
    'info_outline',
    'info_solid',
    'invalid_outline',
    'invalid_solid',
    'invoice_outline',
    'invoice_solid',
    'jpg_outline',
    'jpg_solid',
    'jpy_outline',
    'jpy_solid',
    'key_outline',
    'key_solid',
    'keyboard_outline',
    'keyboard_solid',
    'label_outline',
    'label_solid',
    'layers_outline',
    'layers_solid',
    'layout_outline',
    'layout_solid',
    'left_double_outline',
    'level_up_outline',
    'level_up_solid',
    'library_auditor_outline',
    'library_auditor_solid',
    'light_mode_outline',
    'light_mode_solid',
    'lightning_outline',
    'lightning_solid',
    'line_chart_outline',
    'line_chart_solid',
    'line_spacing_outline',
    'line_through_outline',
    'link_outline',
    'link_solid',
    'list_bulleted_outline',
    'list_numbered_outline',
    'list_style_outline',
    'loader_outline',
    'loader_solid',
    'location_outline',
    'location_solid',
    'lock_outline',
    'lock_solid',
    'magnet_outline',
    'magnet_solid',
    'maintenance_outline',
    'maintenance_solid',
    'male_outline',
    'male_solid',
    'martini_outline',
    'martini_solid',
    'medal_outline',
    'medal_solid',
    'megaphone_outline',
    'megaphone_solid',
    'menu_outline',
    'menu_solid',
    'metro_outline',
    'metro_solid',
    'microphone__off_outline',
    'microphone__off_solid',
    'microphone_outline',
    'microphone_solid',
    'minus_circle_outline',
    'minus_outline',
    'minus_solid',
    'missing_document_outline',
    'missing_document_solid',
    'mobile_outline',
    'mobile_solid',
    'money_outline',
    'money_solid',
    'more_horizontal_outline',
    'more_horizontal_solid',
    'more_vertical_outline',
    'more_vertical_solid',
    'multibonus_outline',
    'multibonus_solid',
    'multicurency_outline',
    'multicurency_solid',
    'nfc_outline',
    'nfc_solid',
    'no_admin_outline',
    'no_admin_solid',
    'no_wifi_outline',
    'no_wifi_solid',
    'notifications_off_outline',
    'notifications_off_solid',
    'notifications_outline',
    'notifications_solid',
    'ok_send_outline',
    'ok_send_solid',
    'open_in_full_outline',
    'open_in_full_solid',
    'openshift_solid',
    'organisation_outline',
    'organisation_solid',
    'palladium_outline',
    'palladium_solid',
    'password_outline',
    'password_solid',
    'pause_outline',
    'pause_solid',
    'pay_cash_outline',
    'pay_cash_solid',
    'payroll_card_outline',
    'payroll_card_solid',
    'pdf_outline',
    'pdf_solid',
    'pension_outline',
    'pension_solid',
    'people_outline',
    'people_solid',
    'person_account_outline',
    'person_account_solid',
    'person_add_outline',
    'person_add_solid',
    'person_card_outline',
    'person_card_solid',
    'person_limit_solid',
    'person_limits_outline',
    'person_outline',
    'person_properties_outline',
    'person_properties_solid',
    'person_refresh_outline',
    'person_refresh_solid',
    'person_solid',
    'person_vip_outline',
    'person_vip_solid',
    'phone_outline',
    'phone_solid',
    'pickup_outline',
    'pickup_solid',
    'pin_outline',
    'pin_solid',
    'plane_outline',
    'plane_solid',
    'platinum_outline',
    'platinum_solid',
    'play_outline',
    'play_solid',
    'plus_circle_outline',
    'plus_circle_solid',
    'plus_outline',
    'plus_solid',
    'post_automat_outline',
    'post_automat_solid',
    'post_outline',
    'post_solid',
    'power_outline',
    'power_solid',
    'ppt_outline',
    'ppt_solid',
    'pregnant_outline',
    'pregnant_solid',
    'print_outline',
    'print_solid',
    'process_outline',
    'process_solid',
    'pull_request_outline',
    'pull_request_solid',
    'ql_outline',
    'ql_solid',
    'qr_code_outline',
    'qr_code_solid',
    'read_check_outline',
    'receipt_favorites_outline',
    'receipt_favorites_solid',
    'receipt_info_outline',
    'receipt_info_solid',
    'receipt_outline',
    'receipt_solid',
    'receipt_update_outline',
    'receipt_update_solid',
    'redo_outline',
    'redo_solid',
    'refuse_outline',
    'refuse_small_outline',
    'refuse_small_solid',
    'refuse_solid',
    'refuse_view_outline',
    'reliz_outline',
    'reliz_solid',
    'report_outline',
    'report_solid',
    'resize_table_outline',
    'right_double_outline',
    'rip_outline',
    'rip_solid',
    'robot_outline',
    'robot_solid',
    'rotate_left_outline',
    'rotate_left_solid',
    'rotate_right_outline',
    'rotate_right_solid',
    'row_delete_outline',
    'row_insert_after_outline',
    'row_insert_below_outline',
    'rub_outline',
    'rub_solid',
    'safety_certificate_outline',
    'safety_certificate_solid',
    'safety_outline',
    'safety_solid',
    'save_outline',
    'save_solid',
    'scan_and_send_outline',
    'scan_and_send_solid',
    'scan_doc_outline',
    'scan_doc_solid',
    'scan_outline',
    'scan_redo_outline',
    'scan_redo_solid',
    'scan_solid',
    'scheme_outline',
    'scheme_solid',
    'search_outline',
    'search_solid',
    'send_sign_outline',
    'send_sign_solid',
    'sent_outline',
    'service_request_outline',
    'service_request_solid',
    'settings_outline',
    'settings_solid',
    'share_outline',
    'share_solid',
    'sharing_outline',
    'sharing_solid',
    'shop_cart_outline',
    'shop_cart_solid',
    'shopping_bag_outline',
    'shopping_bag_solid',
    'show_table_outline',
    'show_table_solid',
    'sign_another_person_outline',
    'sign_another_person_solid',
    'sign_in_outline',
    'sign_in_solid',
    'sign_outline',
    'sign_solid',
    'signal_outline',
    'signal_solid',
    'silver_outline',
    'silver_solid',
    'sim_card_outline',
    'sim_card_solid',
    'size_changer_horizontal_outline',
    'size_changer_vertical_outline',
    'small_arrow_down_outline',
    'small_arrow_down_solid',
    'small_arrow_left_outline',
    'small_arrow_left_solid',
    'small_arrow_right_outline',
    'small_arrow_right_solid',
    'small_arrow_up_outline',
    'small_arrow_up_solid',
    'small_close_outline',
    'small_close_solid',
    'sort_down_outline',
    'sort_down_solid',
    'sort_outline',
    'sort_solid',
    'sort_up_outline',
    'sort_up_solid',
    'source_outline',
    'source_solid',
    'spell_check_outline',
    'star_outline',
    'star_solid',
    'stop_outline',
    'stop_solid',
    'store_outline',
    'store_solid',
    'strim_outline',
    'strim_solid',
    'structure_outline',
    'structure_solid',
    'study_outline',
    'study_solid',
    'subscript_outline',
    'superscript_outline',
    'switch_pinned_areas_outline',
    'switch_pinned_areas_solid',
    'sync_forbid_outline',
    'sync_permit_outline',
    'table_outline',
    'tablet_outline',
    'tablet_solid',
    'tasks_outline',
    'tasks_solid',
    'telegramm_outline',
    'telegramm_solid',
    'test_designer_outline',
    'test_designer_solid',
    'test_manager_outline',
    'test_manager_solid',
    'tester_at_outline',
    'tester_at_solid',
    'tester_ht_outline',
    'tester_ht_solid',
    'tester_outline',
    'tester_solid',
    'text_bold_outline',
    'text_italic_outline',
    'text_underline_outline',
    'third_person_outline',
    'third_person_solid',
    'thumbs_down_outline',
    'thumbs_down_solid',
    'thumbs_up_outline',
    'thumbs_up_solid',
    'time_outline',
    'time_solid',
    'to_customer_outline',
    'to_customer_solid',
    'treasury_outline',
    'treasury_solid',
    'trees_outline',
    'trees_solid',
    'trophy_outline',
    'trophy_solid',
    'tune_outline',
    'tune_solid',
    'txt_color_outline',
    'typography_outline',
    'typography_solid',
    'uah_outline',
    'uah_solid',
    'undo_outline',
    'undo_solid',
    'unlink_outline',
    'unlock_outline',
    'unlock_solid',
    'unsafety_outline',
    'unsafety_solid',
    'unsign_outline',
    'unsign_solid',
    'unwrap_outline',
    'update_outline',
    'update_solid',
    'upload_outline',
    'upload_solid',
    'usb_outline',
    'usb_solid',
    'usd_outline',
    'usd_solid',
    'user_delete_outline',
    'user_delete_solid',
    'user_role_from_outline',
    'user_role_from_solid',
    'user_role_to_outline',
    'user_role_to_solid',
    'utensils_outline',
    'utensils_solid',
    'vacation_outline',
    'vacation_solid',
    'verify_sign_outline',
    'verify_sign_solid',
    'view_history_outline',
    'vip_outline',
    'vip_solid',
    'vote_outline',
    'vote_solid',
    'watcher_outline',
    'watcher_solid',
    'watcher_test_it_outline',
    'watcher_test_it_solid',
    'web_outline',
    'web_solid',
    'webhook_outline',
    'webhook_solid',
    'wifi_outline',
    'wifi_solid',
    'wiki_outline',
    'wiki_solid',
    'work_outline',
    'work_solid',
    'wrap_outline',
    'xls_outline',
    'xls_solid',
    'xml_outline',
    'xml_solid',
    'zip_outline',
    'zip_solid',
    'zoom_in_outline',
    'zoom_in_solid',
    'zoom_out_outline',
    'zoom_out_solid',
  ];
  static Map<String, IconData> iconDataMap = <String, IconData>{
    'accept_outline': AdmiralIcons.admiral_ic_accept_outline,
    'accept_solid': AdmiralIcons.admiral_ic_accept_solid,
    'account_detail_outline': AdmiralIcons.admiral_ic_account_detail_outline,
    'account_detail_solid': AdmiralIcons.admiral_ic_account_detail_solid,
    'acuring_future_outline': AdmiralIcons.admiral_ic_acuring_future_outline,
    'acuring_future_solid': AdmiralIcons.admiral_ic_acuring_future_solid,
    'acuring_modern_outline': AdmiralIcons.admiral_ic_acuring_modern_outline,
    'acuring_modern_solid': AdmiralIcons.admiral_ic_acuring_modern_solid,
    'add_comment_outline': AdmiralIcons.admiral_ic_add_comment_outline,
    'add_comment_solid': AdmiralIcons.admiral_ic_add_comment_solid,
    'add_from_template_outline':
        AdmiralIcons.admiral_ic_add_from_template_outline,
    'add_from_template_solid': AdmiralIcons.admiral_ic_add_from_template_solid,
    'add_template_outline': AdmiralIcons.admiral_ic_add_template_outline,
    'add_template_solid': AdmiralIcons.admiral_ic_add_template_solid,
    'admin_outline': AdmiralIcons.admiral_ic_admin_outline,
    'admin_solid': AdmiralIcons.admiral_ic_admin_solid,
    'administrator_at_outline':
        AdmiralIcons.admiral_ic_administrator_at_outline,
    'administrator_at_solid': AdmiralIcons.admiral_ic_administrator_at_solid,
    'administrator_ht_outline':
        AdmiralIcons.admiral_ic_administrator_ht_outline,
    'administrator_ht_solid': AdmiralIcons.admiral_ic_administrator_ht_solid,
    'agreed_outline': AdmiralIcons.admiral_ic_agreed_outline,
    'agreed_solid': AdmiralIcons.admiral_ic_agreed_solid,
    'alert_outline': AdmiralIcons.admiral_ic_alert_outline,
    'alert_solid': AdmiralIcons.admiral_ic_alert_solid,
    'align_center_outline': AdmiralIcons.admiral_ic_align_center_outline,
    'align_left_outline': AdmiralIcons.admiral_ic_align_left_outline,
    'align_middle_outline': AdmiralIcons.admiral_ic_align_middle_outline,
    'align_right_outline': AdmiralIcons.admiral_ic_align_right_outline,
    'align_top_outline': AdmiralIcons.admiral_ic_align_top_outline,
    'amount_outline': AdmiralIcons.admiral_ic_amount_outline,
    'anchor_outline': AdmiralIcons.admiral_ic_anchor_outline,
    'anchor_solid': AdmiralIcons.admiral_ic_anchor_solid,
    'application_administrator_outline':
        AdmiralIcons.admiral_ic_application_administrator_outline,
    'application_administrator_solid':
        AdmiralIcons.admiral_ic_application_administrator_solid,
    'archive_outline': AdmiralIcons.admiral_ic_archive_outline,
    'archive_solid': AdmiralIcons.admiral_ic_archive_solid,
    'area_chart_outline': AdmiralIcons.admiral_ic_area_chart_outline,
    'area_chart_solid': AdmiralIcons.admiral_ic_area_chart_solid,
    'arrow_cross_outline': AdmiralIcons.admiral_ic_arrow_cross_outline,
    'arrow_cross_solid': AdmiralIcons.admiral_ic_arrow_cross_solid,
    'arrow_down_one_outline': AdmiralIcons.admiral_ic_arrow_down_one_outline,
    'arrow_down_one_solid': AdmiralIcons.admiral_ic_arrow_down_one_solid,
    'arrow_down_outline': AdmiralIcons.admiral_ic_arrow_down_outline,
    'arrow_down_solid': AdmiralIcons.admiral_ic_arrow_down_solid,
    'arrow_down_two_outline': AdmiralIcons.admiral_ic_arrow_down_two_outline,
    'arrow_down_two_solid': AdmiralIcons.admiral_ic_arrow_down_two_solid,
    'arrow_left_outline': AdmiralIcons.admiral_ic_arrow_left_outline,
    'arrow_left_solid': AdmiralIcons.admiral_ic_arrow_left_solid,
    'arrow_right_outline': AdmiralIcons.admiral_ic_arrow_right_outline,
    'arrow_right_solid': AdmiralIcons.admiral_ic_arrow_right_solid,
    'arrow_up_down_outline': AdmiralIcons.admiral_ic_arrow_up_down_outline,
    'arrow_up_down_solid': AdmiralIcons.admiral_ic_arrow_up_down_solid,
    'arrow_up_one_outline': AdmiralIcons.admiral_ic_arrow_up_one_outline,
    'arrow_up_one_solid': AdmiralIcons.admiral_ic_arrow_up_one_solid,
    'arrow_up_outline': AdmiralIcons.admiral_ic_arrow_up_outline,
    'arrow_up_solid': AdmiralIcons.admiral_ic_arrow_up_solid,
    'arrow_up_two_outline': AdmiralIcons.admiral_ic_arrow_up_two_outline,
    'arrow_up_two_solid': AdmiralIcons.admiral_ic_arrow_up_two_solid,
    'arrows_horizontal_outline':
        AdmiralIcons.admiral_ic_arrows_horizontal_outline,
    'arrows_horizontal_solid': AdmiralIcons.admiral_ic_arrows_horizontal_solid,
    'arrows_vertical_outline': AdmiralIcons.admiral_ic_arrows_vertical_outline,
    'arrows_vertical_solid': AdmiralIcons.admiral_ic_arrows_vertical_solid,
    'at_outline': AdmiralIcons.admiral_ic_at_outline,
    'at_solid': AdmiralIcons.admiral_ic_at_solid,
    'attach_file_outline': AdmiralIcons.admiral_ic_attach_file_outline,
    'attach_file_solid': AdmiralIcons.admiral_ic_attach_file_solid,
    'back_outline': AdmiralIcons.admiral_ic_back_outline,
    'back_solid': AdmiralIcons.admiral_ic_back_solid,
    'bank_outline': AdmiralIcons.admiral_ic_bank_outline,
    'bank_solid': AdmiralIcons.admiral_ic_bank_solid,
    'bar_chart__outline': AdmiralIcons.admiral_ic_bar_chart__outline,
    'bar_chart_plus_outline': AdmiralIcons.admiral_ic_bar_chart_plus_outline,
    'bar_chart_plus_solid': AdmiralIcons.admiral_ic_bar_chart_plus_solid,
    'bar_chart_solid': AdmiralIcons.admiral_ic_bar_chart_solid,
    'bar_code_outline': AdmiralIcons.admiral_ic_bar_code_outline,
    'bar_code_solid': AdmiralIcons.admiral_ic_bar_code_solid,
    'bg_color_outline': AdmiralIcons.admiral_ic_bg_color_outline,
    'bonus_outline': AdmiralIcons.admiral_ic_bonus_outline,
    'bonus_ruble_outline': AdmiralIcons.admiral_ic_bonus_ruble_outline,
    'bonus_ruble_solid': AdmiralIcons.admiral_ic_bonus_ruble_solid,
    'bonus_solid': AdmiralIcons.admiral_ic_bonus_solid,
    'book_outline': AdmiralIcons.admiral_ic_book_outline,
    'book_solid': AdmiralIcons.admiral_ic_book_solid,
    'border_bold_bottom_outline':
        AdmiralIcons.admiral_ic_border_bold_bottom_outline,
    'border_bold_left_outline':
        AdmiralIcons.admiral_ic_border_bold_left_outline,
    'border_bold_outter_outline':
        AdmiralIcons.admiral_ic_border_bold_outter_outline,
    'border_bold_right_outline':
        AdmiralIcons.admiral_ic_border_bold_right_outline,
    'border_bold_top_outline': AdmiralIcons.admiral_ic_border_bold_top_outline,
    'border_bottom_outline': AdmiralIcons.admiral_ic_border_bottom_outline,
    'border_clear_outline': AdmiralIcons.admiral_ic_border_clear_outline,
    'border_horizontal_outline':
        AdmiralIcons.admiral_ic_border_horizontal_outline,
    'border_inner_outline': AdmiralIcons.admiral_ic_border_inner_outline,
    'border_left_outline': AdmiralIcons.admiral_ic_border_left_outline,
    'border_outer_outline': AdmiralIcons.admiral_ic_border_outer_outline,
    'border_right_outline': AdmiralIcons.admiral_ic_border_right_outline,
    'border_style_outline': AdmiralIcons.admiral_ic_border_style_outline,
    'border_top_outline': AdmiralIcons.admiral_ic_border_top_outline,
    'border_vertical_outline': AdmiralIcons.admiral_ic_border_vertical_outline,
    'branches_outline': AdmiralIcons.admiral_ic_branches_outline,
    'branches_solid': AdmiralIcons.admiral_ic_branches_solid,
    'broker_outline': AdmiralIcons.admiral_ic_broker_outline,
    'broker_solid': AdmiralIcons.admiral_ic_broker_solid,
    'bug_outline': AdmiralIcons.admiral_ic_bug_outline,
    'bug_solid': AdmiralIcons.admiral_ic_bug_solid,
    'burn_card_outline': AdmiralIcons.admiral_ic_burn_card_outline,
    'burn_card_solid': AdmiralIcons.admiral_ic_burn_card_solid,
    'burn_outline': AdmiralIcons.admiral_ic_burn_outline,
    'burn_solid': AdmiralIcons.admiral_ic_burn_solid,
    'bus_outline': AdmiralIcons.admiral_ic_bus_outline,
    'bus_solid': AdmiralIcons.admiral_ic_bus_solid,
    'calculate_outline': AdmiralIcons.admiral_ic_calculate_outline,
    'calculate_solid': AdmiralIcons.admiral_ic_calculate_solid,
    'calendar_ok_outline': AdmiralIcons.admiral_ic_calendar_ok_outline,
    'calendar_ok_solid': AdmiralIcons.admiral_ic_calendar_ok_solid,
    'calendar_outline': AdmiralIcons.admiral_ic_calendar_outline,
    'calendar_solid': AdmiralIcons.admiral_ic_calendar_solid,
    'calendar_update_outline': AdmiralIcons.admiral_ic_calendar_update_outline,
    'calendar_update_solid': AdmiralIcons.admiral_ic_calendar_update_solid,
    'camera_outline': AdmiralIcons.admiral_ic_camera_outline,
    'camera_remove_outline': AdmiralIcons.admiral_ic_camera_remove_outline,
    'camera_remove_solid': AdmiralIcons.admiral_ic_camera_remove_solid,
    'camera_solid': AdmiralIcons.admiral_ic_camera_solid,
    'cancel_megaphone_outline':
        AdmiralIcons.admiral_ic_cancel_megaphone_outline,
    'cancel_megaphone_solid': AdmiralIcons.admiral_ic_cancel_megaphone_solid,
    'car_outline': AdmiralIcons.admiral_ic_car_outline,
    'car_solid': AdmiralIcons.admiral_ic_car_solid,
    'card_outline': AdmiralIcons.admiral_ic_card_outline,
    'card_solid': AdmiralIcons.admiral_ic_card_solid,
    'card_t_outline': AdmiralIcons.admiral_ic_card_t_outline,
    'card_t_solid': AdmiralIcons.admiral_ic_card_t_solid,
    'card_tp_outline': AdmiralIcons.admiral_ic_card_tp_outline,
    'card_tp_solid': AdmiralIcons.admiral_ic_card_tp_solid,
    'cash_outline': AdmiralIcons.admiral_ic_cash_outline,
    'cash_solid': AdmiralIcons.admiral_ic_cash_solid,
    'cashbox_outline': AdmiralIcons.admiral_ic_cashbox_outline,
    'cashbox_solid': AdmiralIcons.admiral_ic_cashbox_solid,
    'catalog_outline': AdmiralIcons.admiral_ic_catalog_outline,
    'catalog_solid': AdmiralIcons.admiral_ic_catalog_solid,
    'cells_disconnect_outline':
        AdmiralIcons.admiral_ic_cells_disconnect_outline,
    'cells_merge_outline': AdmiralIcons.admiral_ic_cells_merge_outline,
    'chair_outline': AdmiralIcons.admiral_ic_chair_outline,
    'chair_solid': AdmiralIcons.admiral_ic_chair_solid,
    'change_field_outline': AdmiralIcons.admiral_ic_change_field_outline,
    'chart_outline': AdmiralIcons.admiral_ic_chart_outline,
    'chart_solid': AdmiralIcons.admiral_ic_chart_solid,
    'chat_outline': AdmiralIcons.admiral_ic_chat_outline,
    'chat_solid': AdmiralIcons.admiral_ic_chat_solid,
    'check_outline': AdmiralIcons.admiral_ic_check_outline,
    'check_solid': AdmiralIcons.admiral_ic_check_solid,
    'chess_king_outline': AdmiralIcons.admiral_ic_chess_king_outline,
    'chess_king_solid': AdmiralIcons.admiral_ic_chess_king_solid,
    'chevron_down_outline': AdmiralIcons.admiral_ic_chevron_down_outline,
    'chevron_down_solid': AdmiralIcons.admiral_ic_chevron_down_solid,
    'chevron_left_outline': AdmiralIcons.admiral_ic_chevron_left_outline,
    'chevron_left_solid': AdmiralIcons.admiral_ic_chevron_left_solid,
    'chevron_right_outline': AdmiralIcons.admiral_ic_chevron_right_outline,
    'chevron_right_solid': AdmiralIcons.admiral_ic_chevron_right_solid,
    'chevron_up_outline': AdmiralIcons.admiral_ic_chevron_up_outline,
    'chevron_up_solid': AdmiralIcons.admiral_ic_chevron_up_solid,
    'chip_outline': AdmiralIcons.admiral_ic_chip_outline,
    'chip_solid': AdmiralIcons.admiral_ic_chip_solid,
    'clipboard_outline': AdmiralIcons.admiral_ic_clipboard_outline,
    'clipboard_solid': AdmiralIcons.admiral_ic_clipboard_solid,
    'clone_outline': AdmiralIcons.admiral_ic_clone_outline,
    'clone_solid': AdmiralIcons.admiral_ic_clone_solid,
    'close_circle_outline': AdmiralIcons.admiral_ic_close_circle_outline,
    'close_circle_solid': AdmiralIcons.admiral_ic_close_circle_solid,
    'close_fullscreen_outline':
        AdmiralIcons.admiral_ic_close_fullscreen_outline,
    'close_fullscreen_solid': AdmiralIcons.admiral_ic_close_fullscreen_solid,
    'close_outline': AdmiralIcons.admiral_ic_close_outline,
    'close_solid': AdmiralIcons.admiral_ic_close_solid,
    'cloud_done_outline': AdmiralIcons.admiral_ic_cloud_done_outline,
    'cloud_done_solid': AdmiralIcons.admiral_ic_cloud_done_solid,
    'cloud_not_available_outline':
        AdmiralIcons.admiral_ic_cloud_not_available_outline,
    'cloud_not_available_solid':
        AdmiralIcons.admiral_ic_cloud_not_available_solid,
    'cloud_outline': AdmiralIcons.admiral_ic_cloud_outline,
    'cloud_solid': AdmiralIcons.admiral_ic_cloud_solid,
    'cloud_upload_outline': AdmiralIcons.admiral_ic_cloud_upload_outline,
    'cloud_upload_solid': AdmiralIcons.admiral_ic_cloud_upload_solid,
    'color_outline': AdmiralIcons.admiral_ic_color_outline,
    'color_solid': AdmiralIcons.admiral_ic_color_solid,
    'column_delete_outline': AdmiralIcons.admiral_ic_column_delete_outline,
    'column_insert_after_outline':
        AdmiralIcons.admiral_ic_column_insert_after_outline,
    'column_insert_before_outline':
        AdmiralIcons.admiral_ic_column_insert_before_outline,
    'columns_outline': AdmiralIcons.admiral_ic_columns_outline,
    'comment_outline': AdmiralIcons.admiral_ic_comment_outline,
    'comment_solid': AdmiralIcons.admiral_ic_comment_solid,
    'commits_outline': AdmiralIcons.admiral_ic_commits_outline,
    'commits_solid': AdmiralIcons.admiral_ic_commits_solid,
    'compare_outline': AdmiralIcons.admiral_ic_compare_outline,
    'compare_solid': AdmiralIcons.admiral_ic_compare_solid,
    'component_outline': AdmiralIcons.admiral_ic_component_outline,
    'component_solid': AdmiralIcons.admiral_ic_component_solid,
    'component_template_outline':
        AdmiralIcons.admiral_ic_component_template_outline,
    'component_template_solid':
        AdmiralIcons.admiral_ic_component_template_solid,
    'copy_outline': AdmiralIcons.admiral_ic_copy_outline,
    'copy_solid': AdmiralIcons.admiral_ic_copy_solid,
    'create_branches_outline': AdmiralIcons.admiral_ic_create_branches_outline,
    'create_branches_solid': AdmiralIcons.admiral_ic_create_branches_solid,
    'create_fork_outline': AdmiralIcons.admiral_ic_create_fork_outline,
    'create_fork_solid': AdmiralIcons.admiral_ic_create_fork_solid,
    'create_pull_request_outline':
        AdmiralIcons.admiral_ic_create_pull_request_outline,
    'create_pull_request_solid':
        AdmiralIcons.admiral_ic_create_pull_request_solid,
    'credit_card_outline': AdmiralIcons.admiral_ic_credit_card_outline,
    'credit_card_solid': AdmiralIcons.admiral_ic_credit_card_solid,
    'credit_outline': AdmiralIcons.admiral_ic_credit_outline,
    'credit_solid': AdmiralIcons.admiral_ic_credit_solid,
    'cube_outline': AdmiralIcons.admiral_ic_cube_outline,
    'cube_solid': AdmiralIcons.admiral_ic_cube_solid,
    'cut_outline': AdmiralIcons.admiral_ic_cut_outline,
    'cut_solid': AdmiralIcons.admiral_ic_cut_solid,
    'cvv_outline': AdmiralIcons.admiral_ic_cvv_outline,
    'cvv_solid': AdmiralIcons.admiral_ic_cvv_solid,
    'danger_outline': AdmiralIcons.admiral_ic_danger_outline,
    'danger_solid': AdmiralIcons.admiral_ic_danger_solid,
    'dark_mode_outline': AdmiralIcons.admiral_ic_dark_mode_outline,
    'dark_mode_solid': AdmiralIcons.admiral_ic_dark_mode_solid,
    'debit_card_outline': AdmiralIcons.admiral_ic_debit_card_outline,
    'debit_card_solid': AdmiralIcons.admiral_ic_debit_card_solid,
    'delete_docs_outline': AdmiralIcons.admiral_ic_delete_docs_outline,
    'delete_docs_solid': AdmiralIcons.admiral_ic_delete_docs_solid,
    'delete_document_outline': AdmiralIcons.admiral_ic_delete_document_outline,
    'delete_document_solid': AdmiralIcons.admiral_ic_delete_document_solid,
    'delete_outline': AdmiralIcons.admiral_ic_delete_outline,
    'delete_solid': AdmiralIcons.admiral_ic_delete_solid,
    'delete_style_outline': AdmiralIcons.admiral_ic_delete_style_outline,
    'delete_table_outline': AdmiralIcons.admiral_ic_delete_table_outline,
    'delivery_outline': AdmiralIcons.admiral_ic_delivery_outline,
    'delivery_solid': AdmiralIcons.admiral_ic_delivery_solid,
    'deposit_outline': AdmiralIcons.admiral_ic_deposit_outline,
    'deposit_solid': AdmiralIcons.admiral_ic_deposit_solid,
    'description_outline': AdmiralIcons.admiral_ic_description_outline,
    'description_solid': AdmiralIcons.admiral_ic_description_solid,
    'desktop_outline': AdmiralIcons.admiral_ic_desktop_outline,
    'desktop_solid': AdmiralIcons.admiral_ic_desktop_solid,
    'developer_outline': AdmiralIcons.admiral_ic_developer_outline,
    'developer_solid': AdmiralIcons.admiral_ic_developer_solid,
    'devops_engineer_outline': AdmiralIcons.admiral_ic_devops_engineer_outline,
    'devops_engineer_solid': AdmiralIcons.admiral_ic_devops_engineer_solid,
    'diamond_outline': AdmiralIcons.admiral_ic_diamond_outline,
    'diamond_solid': AdmiralIcons.admiral_ic_diamond_solid,
    'digitalmoney_outline': AdmiralIcons.admiral_ic_digitalmoney_outline,
    'digitalmoney_solid': AdmiralIcons.admiral_ic_digitalmoney_solid,
    'doc_attention_outline': AdmiralIcons.admiral_ic_doc_attention_outline,
    'doc_attention_solid': AdmiralIcons.admiral_ic_doc_attention_solid,
    'doc_export_outline': AdmiralIcons.admiral_ic_doc_export_outline,
    'doc_export_solid': AdmiralIcons.admiral_ic_doc_export_solid,
    'doc_finished_outline': AdmiralIcons.admiral_ic_doc_finished_outline,
    'doc_finished_solid': AdmiralIcons.admiral_ic_doc_finished_solid,
    'doc_ok_outline': AdmiralIcons.admiral_ic_doc_ok_outline,
    'doc_ok_solid': AdmiralIcons.admiral_ic_doc_ok_solid,
    'doc_operations_outline': AdmiralIcons.admiral_ic_doc_operations_outline,
    'doc_operations_solid': AdmiralIcons.admiral_ic_doc_operations_solid,
    'doc_processing_outline': AdmiralIcons.admiral_ic_doc_processing_outline,
    'doc_processing_solid': AdmiralIcons.admiral_ic_doc_processing_solid,
    'doc_regenerate_outline': AdmiralIcons.admiral_ic_doc_regenerate_outline,
    'doc_regenerate_solid': AdmiralIcons.admiral_ic_doc_regenerate_solid,
    'doc_settings_outline': AdmiralIcons.admiral_ic_doc_settings_outline,
    'doc_settings_solid': AdmiralIcons.admiral_ic_doc_settings_solid,
    'doc_sign_outline': AdmiralIcons.admiral_ic_doc_sign_outline,
    'doc_sign_solid': AdmiralIcons.admiral_ic_doc_sign_solid,
    'doc_sign_verify_outline': AdmiralIcons.admiral_ic_doc_sign_verify_outline,
    'doc_sign_verify_solid': AdmiralIcons.admiral_ic_doc_sign_verify_solid,
    'doc_view_outline': AdmiralIcons.admiral_ic_doc_view_outline,
    'doc_view_solid': AdmiralIcons.admiral_ic_doc_view_solid,
    'docs_outline': AdmiralIcons.admiral_ic_docs_outline,
    'docs_solid': AdmiralIcons.admiral_ic_docs_solid,
    'document_add_outline': AdmiralIcons.admiral_ic_document_add_outline,
    'document_add_solid': AdmiralIcons.admiral_ic_document_add_solid,
    'dots_menu_outline': AdmiralIcons.admiral_ic_dots_menu_outline,
    'dots_menu_solid': AdmiralIcons.admiral_ic_dots_menu_solid,
    'double_arrow_down_outline':
        AdmiralIcons.admiral_ic_double_arrow_down_outline,
    'double_arrow_down_solid': AdmiralIcons.admiral_ic_double_arrow_down_solid,
    'double_arrow_left_outline':
        AdmiralIcons.admiral_ic_double_arrow_left_outline,
    'double_arrow_left_solid': AdmiralIcons.admiral_ic_double_arrow_left_solid,
    'double_arrow_right_outline':
        AdmiralIcons.admiral_ic_double_arrow_right_outline,
    'double_arrow_right_solid':
        AdmiralIcons.admiral_ic_double_arrow_right_solid,
    'double_arrow_up_outline': AdmiralIcons.admiral_ic_double_arrow_up_outline,
    'double_arrow_up_solid': AdmiralIcons.admiral_ic_double_arrow_up_solid,
    'download_outline': AdmiralIcons.admiral_ic_download_outline,
    'download_solid': AdmiralIcons.admiral_ic_download_solid,
    'drag_outline': AdmiralIcons.admiral_ic_drag_outline,
    'drag_solid': AdmiralIcons.admiral_ic_drag_solid,
    'duplicate_outline': AdmiralIcons.admiral_ic_duplicate_outline,
    'duplicate_solid': AdmiralIcons.admiral_ic_duplicate_solid,
    'edit_outline': AdmiralIcons.admiral_ic_edit_outline,
    'edit_solid': AdmiralIcons.admiral_ic_edit_solid,
    'elderly_outline': AdmiralIcons.admiral_ic_elderly_outline,
    'elderly_solid': AdmiralIcons.admiral_ic_elderly_solid,
    'element_fixed_outline': AdmiralIcons.admiral_ic_element_fixed_outline,
    'element_grow_horizontally_outline':
        AdmiralIcons.admiral_ic_element_grow_horizontally_outline,
    'element_grow_vertically_outline':
        AdmiralIcons.admiral_ic_element_grow_vertically_outline,
    'email_outline': AdmiralIcons.admiral_ic_email_outline,
    'email_read_outline': AdmiralIcons.admiral_ic_email_read_outline,
    'email_read_solid': AdmiralIcons.admiral_ic_email_read_solid,
    'email_solid': AdmiralIcons.admiral_ic_email_solid,
    'emoji_neutal_outline': AdmiralIcons.admiral_ic_emoji_neutal_outline,
    'emoji_neutral_solid': AdmiralIcons.admiral_ic_emoji_neutral_solid,
    'emoji_sad_outline': AdmiralIcons.admiral_ic_emoji_sad_outline,
    'emoji_sad_solid': AdmiralIcons.admiral_ic_emoji_sad_solid,
    'emoji_smile_outline': AdmiralIcons.admiral_ic_emoji_smile_outline,
    'emoji_smile_solid': AdmiralIcons.admiral_ic_emoji_smile_solid,
    'envelope_outline': AdmiralIcons.admiral_ic_envelope_outline,
    'envelope_solid': AdmiralIcons.admiral_ic_envelope_solid,
    'equally_outline': AdmiralIcons.admiral_ic_equally_outline,
    'equally_solid': AdmiralIcons.admiral_ic_equally_solid,
    'eraser_outline': AdmiralIcons.admiral_ic_eraser_outline,
    'eraser_solid': AdmiralIcons.admiral_ic_eraser_solid,
    'error_outline': AdmiralIcons.admiral_ic_error_outline,
    'error_solid': AdmiralIcons.admiral_ic_error_solid,
    'error_triangle_outline': AdmiralIcons.admiral_ic_error_triangle_outline,
    'error_triangle_solid': AdmiralIcons.admiral_ic_error_triangle_solid,
    'eur_outline': AdmiralIcons.admiral_ic_eur_outline,
    'eur_solid': AdmiralIcons.admiral_ic_eur_solid,
    'exit_outline': AdmiralIcons.admiral_ic_exit_outline,
    'exit_solid': AdmiralIcons.admiral_ic_exit_solid,
    'export_outline': AdmiralIcons.admiral_ic_export_outline,
    'export_solid': AdmiralIcons.admiral_ic_export_solid,
    'eye_close_outline': AdmiralIcons.admiral_ic_eye_close_outline,
    'eye_off_outline': AdmiralIcons.admiral_ic_eye_off_outline,
    'eye_off_solid': AdmiralIcons.admiral_ic_eye_off_solid,
    'eye_outline': AdmiralIcons.admiral_ic_eye_outline,
    'eye_solid': AdmiralIcons.admiral_ic_eye_solid,
    'eyedropper_outline': AdmiralIcons.admiral_ic_eyedropper_outline,
    'eyedropper_solid': AdmiralIcons.admiral_ic_eyedropper_solid,
    'faceid_outline': AdmiralIcons.admiral_ic_faceid_outline,
    'faceid_solid': AdmiralIcons.admiral_ic_faceid_solid,
    'file_csv_outline': AdmiralIcons.admiral_ic_file_csv_outline,
    'file_csv_solid': AdmiralIcons.admiral_ic_file_csv_solid,
    'file_currency_outline': AdmiralIcons.admiral_ic_file_currency_outline,
    'file_currency_solid': AdmiralIcons.admiral_ic_file_currency_solid,
    'file_doc_outline': AdmiralIcons.admiral_ic_file_doc_outline,
    'file_doc_solid': AdmiralIcons.admiral_ic_file_doc_solid,
    'file_jpg_outline': AdmiralIcons.admiral_ic_file_jpg_outline,
    'file_jpg_solid': AdmiralIcons.admiral_ic_file_jpg_solid,
    'file_pdf_outline': AdmiralIcons.admiral_ic_file_pdf_outline,
    'file_pdf_solid': AdmiralIcons.admiral_ic_file_pdf_solid,
    'file_ppt_outline': AdmiralIcons.admiral_ic_file_ppt_outline,
    'file_ppt_solid': AdmiralIcons.admiral_ic_file_ppt_solid,
    'file_sng_outline': AdmiralIcons.admiral_ic_file_sng_outline,
    'file_sng_solid': AdmiralIcons.admiral_ic_file_sng_solid,
    'file_tif_outline': AdmiralIcons.admiral_ic_file_tif_outline,
    'file_tif_solid': AdmiralIcons.admiral_ic_file_tif_solid,
    'file_tiff_outline': AdmiralIcons.admiral_ic_file_tiff_outline,
    'file_tiff_solid': AdmiralIcons.admiral_ic_file_tiff_solid,
    'file_txt_outline': AdmiralIcons.admiral_ic_file_txt_outline,
    'file_txt_solid': AdmiralIcons.admiral_ic_file_txt_solid,
    'file_word_outline': AdmiralIcons.admiral_ic_file_word_outline,
    'file_word_solid': AdmiralIcons.admiral_ic_file_word_solid,
    'file_xls_outline': AdmiralIcons.admiral_ic_file_xls_outline,
    'file_xls_solid': AdmiralIcons.admiral_ic_file_xls_solid,
    'file_xml_outline': AdmiralIcons.admiral_ic_file_xml_outline,
    'file_xml_solid': AdmiralIcons.admiral_ic_file_xml_solid,
    'filter_outline': AdmiralIcons.admiral_ic_filter_outline,
    'filter_solid': AdmiralIcons.admiral_ic_filter_solid,
    'finance_outline': AdmiralIcons.admiral_ic_finance_outline,
    'finance_solid': AdmiralIcons.admiral_ic_finance_solid,
    'fingerprint_outline': AdmiralIcons.admiral_ic_fingerprint_outline,
    'fingerprint_solid': AdmiralIcons.admiral_ic_fingerprint_solid,
    'flag_outline': AdmiralIcons.admiral_ic_flag_outline,
    'flag_solid': AdmiralIcons.admiral_ic_flag_solid,
    'flash_light_outline': AdmiralIcons.admiral_ic_flash_light_outline,
    'flash_light_solid': AdmiralIcons.admiral_ic_flash_light_solid,
    'folder_outline': AdmiralIcons.admiral_ic_folder_outline,
    'folder_solid': AdmiralIcons.admiral_ic_folder_solid,
    'font_style_outline': AdmiralIcons.admiral_ic_font_style_outline,
    'forks_outline': AdmiralIcons.admiral_ic_forks_outline,
    'forks_solid': AdmiralIcons.admiral_ic_forks_solid,
    'format_align_justify_outline':
        AdmiralIcons.admiral_ic_format_align_justify_outline,
    'format_paint_outline': AdmiralIcons.admiral_ic_format_paint_outline,
    'format_paint_solid': AdmiralIcons.admiral_ic_format_paint_solid,
    'gallery_outline': AdmiralIcons.admiral_ic_gallery_outline,
    'gallery_solid': AdmiralIcons.admiral_ic_gallery_solid,
    'game_outline': AdmiralIcons.admiral_ic_game_outline,
    'game_solid': AdmiralIcons.admiral_ic_game_solid,
    'gantt_chart_outline': AdmiralIcons.admiral_ic_gantt_chart_outline,
    'gantt_chart_solid': AdmiralIcons.admiral_ic_gantt_chart_solid,
    'gbp_outline': AdmiralIcons.admiral_ic_gbp_outline,
    'gbp_solid': AdmiralIcons.admiral_ic_gbp_solid,
    'get_cash_outline': AdmiralIcons.admiral_ic_get_cash_outline,
    'get_cash_solid': AdmiralIcons.admiral_ic_get_cash_solid,
    'globe_outline': AdmiralIcons.admiral_ic_globe_outline,
    'globe_solid': AdmiralIcons.admiral_ic_globe_solid,
    'gold_outline': AdmiralIcons.admiral_ic_gold_outline,
    'gold_solid': AdmiralIcons.admiral_ic_gold_solid,
    'government_outline': AdmiralIcons.admiral_ic_government_outline,
    'government_solid': AdmiralIcons.admiral_ic_government_solid,
    'gps_outline': AdmiralIcons.admiral_ic_gps_outline,
    'gps_solid': AdmiralIcons.admiral_ic_gps_solid,
    'grid_outline': AdmiralIcons.admiral_ic_grid_outline,
    'grid_solid': AdmiralIcons.admiral_ic_grid_solid,
    'group_objects_outline': AdmiralIcons.admiral_ic_group_objects_outline,
    'group_objects_solid': AdmiralIcons.admiral_ic_group_objects_solid,
    'headset_outline': AdmiralIcons.admiral_ic_headset_outline,
    'headset_solid': AdmiralIcons.admiral_ic_headset_solid,
    'heart_outline': AdmiralIcons.admiral_ic_heart_outline,
    'heart_solid': AdmiralIcons.admiral_ic_heart_solid,
    'help_outline': AdmiralIcons.admiral_ic_help_outline,
    'help_solid': AdmiralIcons.admiral_ic_help_solid,
    'hide_left_panel_outline': AdmiralIcons.admiral_ic_hide_left_panel_outline,
    'hide_right_panel_outline':
        AdmiralIcons.admiral_ic_hide_right_panel_outline,
    'hierarchy_outline': AdmiralIcons.admiral_ic_hierarchy_outline,
    'hierarchy_solid': AdmiralIcons.admiral_ic_hierarchy_solid,
    'home_autocredit_outline': AdmiralIcons.admiral_ic_home_autocredit_outline,
    'home_autocredit_solid': AdmiralIcons.admiral_ic_home_autocredit_solid,
    'home_outline': AdmiralIcons.admiral_ic_home_outline,
    'home_solid': AdmiralIcons.admiral_ic_home_solid,
    'hook_outline': AdmiralIcons.admiral_ic_hook_outline,
    'hook_solid': AdmiralIcons.admiral_ic_hook_solid,
    'huge_procent_outline': AdmiralIcons.admiral_ic_huge_procent_outline,
    'huge_procent_solid': AdmiralIcons.admiral_ic_huge_procent_solid,
    'icons_outline': AdmiralIcons.admiral_ic_icons_outline,
    'icons_solid': AdmiralIcons.admiral_ic_icons_solid,
    'idea_outline': AdmiralIcons.admiral_ic_idea_outline,
    'idea_solid': AdmiralIcons.admiral_ic_idea_solid,
    'iis_outline': AdmiralIcons.admiral_ic_iis_outline,
    'iis_solid': AdmiralIcons.admiral_ic_iis_solid,
    'import_outline': AdmiralIcons.admiral_ic_import_outline,
    'import_solid': AdmiralIcons.admiral_ic_import_solid,
    'inbox_outline': AdmiralIcons.admiral_ic_inbox_outline,
    'inbox_solid': AdmiralIcons.admiral_ic_inbox_solid,
    'incognito_outline': AdmiralIcons.admiral_ic_incognito_outline,
    'incognito_solid': AdmiralIcons.admiral_ic_incognito_solid,
    'indent_decrease_outline': AdmiralIcons.admiral_ic_indent_decrease_outline,
    'indent_increase_outline': AdmiralIcons.admiral_ic_indent_increase_outline,
    'info_outline': AdmiralIcons.admiral_ic_info_outline,
    'info_solid': AdmiralIcons.admiral_ic_info_solid,
    'invalid_outline': AdmiralIcons.admiral_ic_invalid_outline,
    'invalid_solid': AdmiralIcons.admiral_ic_invalid_solid,
    'invoice_outline': AdmiralIcons.admiral_ic_invoice_outline,
    'invoice_solid': AdmiralIcons.admiral_ic_invoice_solid,
    'jpg_outline': AdmiralIcons.admiral_ic_jpg_outline,
    'jpg_solid': AdmiralIcons.admiral_ic_jpg_solid,
    'jpy_outline': AdmiralIcons.admiral_ic_jpy_outline,
    'jpy_solid': AdmiralIcons.admiral_ic_jpy_solid,
    'key_outline': AdmiralIcons.admiral_ic_key_outline,
    'key_solid': AdmiralIcons.admiral_ic_key_solid,
    'keyboard_outline': AdmiralIcons.admiral_ic_keyboard_outline,
    'keyboard_solid': AdmiralIcons.admiral_ic_keyboard_solid,
    'label_outline': AdmiralIcons.admiral_ic_label_outline,
    'label_solid': AdmiralIcons.admiral_ic_label_solid,
    'layers_outline': AdmiralIcons.admiral_ic_layers_outline,
    'layers_solid': AdmiralIcons.admiral_ic_layers_solid,
    'layout_outline': AdmiralIcons.admiral_ic_layout_outline,
    'layout_solid': AdmiralIcons.admiral_ic_layout_solid,
    'left_double_outline': AdmiralIcons.admiral_ic_left_double_outline,
    'level_up_outline': AdmiralIcons.admiral_ic_level_up_outline,
    'level_up_solid': AdmiralIcons.admiral_ic_level_up_solid,
    'library_auditor_outline': AdmiralIcons.admiral_ic_library_auditor_outline,
    'library_auditor_solid': AdmiralIcons.admiral_ic_library_auditor_solid,
    'light_mode_outline': AdmiralIcons.admiral_ic_light_mode_outline,
    'light_mode_solid': AdmiralIcons.admiral_ic_light_mode_solid,
    'lightning_outline': AdmiralIcons.admiral_ic_lightning_outline,
    'lightning_solid': AdmiralIcons.admiral_ic_lightning_solid,
    'line_chart_outline': AdmiralIcons.admiral_ic_line_chart_outline,
    'line_chart_solid': AdmiralIcons.admiral_ic_line_chart_solid,
    'line_spacing_outline': AdmiralIcons.admiral_ic_line_spacing_outline,
    'line_through_outline': AdmiralIcons.admiral_ic_line_through_outline,
    'link_outline': AdmiralIcons.admiral_ic_link_outline,
    'link_solid': AdmiralIcons.admiral_ic_link_solid,
    'list_bulleted_outline': AdmiralIcons.admiral_ic_list_bulleted_outline,
    'list_numbered_outline': AdmiralIcons.admiral_ic_list_numbered_outline,
    'list_style_outline': AdmiralIcons.admiral_ic_list_style_outline,
    'loader_outline': AdmiralIcons.admiral_ic_loader_outline,
    'loader_solid': AdmiralIcons.admiral_ic_loader_solid,
    'location_outline': AdmiralIcons.admiral_ic_location_outline,
    'location_solid': AdmiralIcons.admiral_ic_location_solid,
    'lock_outline': AdmiralIcons.admiral_ic_lock_outline,
    'lock_solid': AdmiralIcons.admiral_ic_lock_solid,
    'magnet_outline': AdmiralIcons.admiral_ic_magnet_outline,
    'magnet_solid': AdmiralIcons.admiral_ic_magnet_solid,
    'maintenance_outline': AdmiralIcons.admiral_ic_maintenance_outline,
    'maintenance_solid': AdmiralIcons.admiral_ic_maintenance_solid,
    'male_outline': AdmiralIcons.admiral_ic_male_outline,
    'male_solid': AdmiralIcons.admiral_ic_male_solid,
    'martini_outline': AdmiralIcons.admiral_ic_martini_outline,
    'martini_solid': AdmiralIcons.admiral_ic_martini_solid,
    'medal_outline': AdmiralIcons.admiral_ic_medal_outline,
    'medal_solid': AdmiralIcons.admiral_ic_medal_solid,
    'megaphone_outline': AdmiralIcons.admiral_ic_megaphone_outline,
    'megaphone_solid': AdmiralIcons.admiral_ic_megaphone_solid,
    'menu_outline': AdmiralIcons.admiral_ic_menu_outline,
    'menu_solid': AdmiralIcons.admiral_ic_menu_solid,
    'metro_outline': AdmiralIcons.admiral_ic_metro_outline,
    'metro_solid': AdmiralIcons.admiral_ic_metro_solid,
    'microphone__off_outline': AdmiralIcons.admiral_ic_microphone__off_outline,
    'microphone__off_solid': AdmiralIcons.admiral_ic_microphone__off_solid,
    'microphone_outline': AdmiralIcons.admiral_ic_microphone_outline,
    'microphone_solid': AdmiralIcons.admiral_ic_microphone_solid,
    'minus_circle_outline': AdmiralIcons.admiral_ic_minus_circle_outline,
    'minus_outline': AdmiralIcons.admiral_ic_minus_outline,
    'minus_solid': AdmiralIcons.admiral_ic_minus_solid,
    'missing_document_outline':
        AdmiralIcons.admiral_ic_missing_document_outline,
    'missing_document_solid': AdmiralIcons.admiral_ic_missing_document_solid,
    'mobile_outline': AdmiralIcons.admiral_ic_mobile_outline,
    'mobile_solid': AdmiralIcons.admiral_ic_mobile_solid,
    'money_outline': AdmiralIcons.admiral_ic_money_outline,
    'money_solid': AdmiralIcons.admiral_ic_money_solid,
    'more_horizontal_outline': AdmiralIcons.admiral_ic_more_horizontal_outline,
    'more_horizontal_solid': AdmiralIcons.admiral_ic_more_horizontal_solid,
    'more_vertical_outline': AdmiralIcons.admiral_ic_more_vertical_outline,
    'more_vertical_solid': AdmiralIcons.admiral_ic_more_vertical_solid,
    'multibonus_outline': AdmiralIcons.admiral_ic_multibonus_outline,
    'multibonus_solid': AdmiralIcons.admiral_ic_multibonus_solid,
    'multicurency_outline': AdmiralIcons.admiral_ic_multicurency_outline,
    'multicurency_solid': AdmiralIcons.admiral_ic_multicurency_solid,
    'nfc_outline': AdmiralIcons.admiral_ic_nfc_outline,
    'nfc_solid': AdmiralIcons.admiral_ic_nfc_solid,
    'no_admin_outline': AdmiralIcons.admiral_ic_no_admin_outline,
    'no_admin_solid': AdmiralIcons.admiral_ic_no_admin_solid,
    'no_wifi_outline': AdmiralIcons.admiral_ic_no_wifi_outline,
    'no_wifi_solid': AdmiralIcons.admiral_ic_no_wifi_solid,
    'notifications_off_outline':
        AdmiralIcons.admiral_ic_notifications_off_outline,
    'notifications_off_solid': AdmiralIcons.admiral_ic_notifications_off_solid,
    'notifications_outline': AdmiralIcons.admiral_ic_notifications_outline,
    'notifications_solid': AdmiralIcons.admiral_ic_notifications_solid,
    'ok_send_outline': AdmiralIcons.admiral_ic_ok_send_outline,
    'ok_send_solid': AdmiralIcons.admiral_ic_ok_send_solid,
    'open_in_full_outline': AdmiralIcons.admiral_ic_open_in_full_outline,
    'open_in_full_solid': AdmiralIcons.admiral_ic_open_in_full_solid,
    'openshift_solid': AdmiralIcons.admiral_ic_openshift_solid,
    'organisation_outline': AdmiralIcons.admiral_ic_organisation_outline,
    'organisation_solid': AdmiralIcons.admiral_ic_organisation_solid,
    'palladium_outline': AdmiralIcons.admiral_ic_palladium_outline,
    'palladium_solid': AdmiralIcons.admiral_ic_palladium_solid,
    'password_outline': AdmiralIcons.admiral_ic_password_outline,
    'password_solid': AdmiralIcons.admiral_ic_password_solid,
    'pause_outline': AdmiralIcons.admiral_ic_pause_outline,
    'pause_solid': AdmiralIcons.admiral_ic_pause_solid,
    'pay_cash_outline': AdmiralIcons.admiral_ic_pay_cash_outline,
    'pay_cash_solid': AdmiralIcons.admiral_ic_pay_cash_solid,
    'payroll_card_outline': AdmiralIcons.admiral_ic_payroll_card_outline,
    'payroll_card_solid': AdmiralIcons.admiral_ic_payroll_card_solid,
    'pdf_outline': AdmiralIcons.admiral_ic_pdf_outline,
    'pdf_solid': AdmiralIcons.admiral_ic_pdf_solid,
    'pension_outline': AdmiralIcons.admiral_ic_pension_outline,
    'pension_solid': AdmiralIcons.admiral_ic_pension_solid,
    'people_outline': AdmiralIcons.admiral_ic_people_outline,
    'people_solid': AdmiralIcons.admiral_ic_people_solid,
    'person_account_outline': AdmiralIcons.admiral_ic_person_account_outline,
    'person_account_solid': AdmiralIcons.admiral_ic_person_account_solid,
    'person_add_outline': AdmiralIcons.admiral_ic_person_add_outline,
    'person_add_solid': AdmiralIcons.admiral_ic_person_add_solid,
    'person_card_outline': AdmiralIcons.admiral_ic_person_card_outline,
    'person_card_solid': AdmiralIcons.admiral_ic_person_card_solid,
    'person_limit_solid': AdmiralIcons.admiral_ic_person_limit_solid,
    'person_limits_outline': AdmiralIcons.admiral_ic_person_limits_outline,
    'person_outline': AdmiralIcons.admiral_ic_person_outline,
    'person_properties_outline':
        AdmiralIcons.admiral_ic_person_properties_outline,
    'person_properties_solid': AdmiralIcons.admiral_ic_person_properties_solid,
    'person_refresh_outline': AdmiralIcons.admiral_ic_person_refresh_outline,
    'person_refresh_solid': AdmiralIcons.admiral_ic_person_refresh_solid,
    'person_solid': AdmiralIcons.admiral_ic_person_solid,
    'person_vip_outline': AdmiralIcons.admiral_ic_person_vip_outline,
    'person_vip_solid': AdmiralIcons.admiral_ic_person_vip_solid,
    'phone_outline': AdmiralIcons.admiral_ic_phone_outline,
    'phone_solid': AdmiralIcons.admiral_ic_phone_solid,
    'pickup_outline': AdmiralIcons.admiral_ic_pickup_outline,
    'pickup_solid': AdmiralIcons.admiral_ic_pickup_solid,
    'pin_outline': AdmiralIcons.admiral_ic_pin_outline,
    'pin_solid': AdmiralIcons.admiral_ic_pin_solid,
    'plane_outline': AdmiralIcons.admiral_ic_plane_outline,
    'plane_solid': AdmiralIcons.admiral_ic_plane_solid,
    'platinum_outline': AdmiralIcons.admiral_ic_platinum_outline,
    'platinum_solid': AdmiralIcons.admiral_ic_platinum_solid,
    'play_outline': AdmiralIcons.admiral_ic_play_outline,
    'play_solid': AdmiralIcons.admiral_ic_play_solid,
    'plus_circle_outline': AdmiralIcons.admiral_ic_plus_circle_outline,
    'plus_circle_solid': AdmiralIcons.admiral_ic_plus_circle_solid,
    'plus_outline': AdmiralIcons.admiral_ic_plus_outline,
    'plus_solid': AdmiralIcons.admiral_ic_plus_solid,
    'post_automat_outline': AdmiralIcons.admiral_ic_post_automat_outline,
    'post_automat_solid': AdmiralIcons.admiral_ic_post_automat_solid,
    'post_outline': AdmiralIcons.admiral_ic_post_outline,
    'post_solid': AdmiralIcons.admiral_ic_post_solid,
    'power_outline': AdmiralIcons.admiral_ic_power_outline,
    'power_solid': AdmiralIcons.admiral_ic_power_solid,
    'ppt_outline': AdmiralIcons.admiral_ic_ppt_outline,
    'ppt_solid': AdmiralIcons.admiral_ic_ppt_solid,
    'pregnant_outline': AdmiralIcons.admiral_ic_pregnant_outline,
    'pregnant_solid': AdmiralIcons.admiral_ic_pregnant_solid,
    'print_outline': AdmiralIcons.admiral_ic_print_outline,
    'print_solid': AdmiralIcons.admiral_ic_print_solid,
    'process_outline': AdmiralIcons.admiral_ic_process_outline,
    'process_solid': AdmiralIcons.admiral_ic_process_solid,
    'pull_request_outline': AdmiralIcons.admiral_ic_pull_request_outline,
    'pull_request_solid': AdmiralIcons.admiral_ic_pull_request_solid,
    'ql_outline': AdmiralIcons.admiral_ic_ql_outline,
    'ql_solid': AdmiralIcons.admiral_ic_ql_solid,
    'qr_code_outline': AdmiralIcons.admiral_ic_qr_code_outline,
    'qr_code_solid': AdmiralIcons.admiral_ic_qr_code_solid,
    'read_check_outline': AdmiralIcons.admiral_ic_read_check_outline,
    'receipt_favorites_outline':
        AdmiralIcons.admiral_ic_receipt_favorites_outline,
    'receipt_favorites_solid': AdmiralIcons.admiral_ic_receipt_favorites_solid,
    'receipt_info_outline': AdmiralIcons.admiral_ic_receipt_info_outline,
    'receipt_info_solid': AdmiralIcons.admiral_ic_receipt_info_solid,
    'receipt_outline': AdmiralIcons.admiral_ic_receipt_outline,
    'receipt_solid': AdmiralIcons.admiral_ic_receipt_solid,
    'receipt_update_outline': AdmiralIcons.admiral_ic_receipt_update_outline,
    'receipt_update_solid': AdmiralIcons.admiral_ic_receipt_update_solid,
    'redo_outline': AdmiralIcons.admiral_ic_redo_outline,
    'redo_solid': AdmiralIcons.admiral_ic_redo_solid,
    'refuse_outline': AdmiralIcons.admiral_ic_refuse_outline,
    'refuse_small_outline': AdmiralIcons.admiral_ic_refuse_small_outline,
    'refuse_small_solid': AdmiralIcons.admiral_ic_refuse_small_solid,
    'refuse_solid': AdmiralIcons.admiral_ic_refuse_solid,
    'refuse_view_outline': AdmiralIcons.admiral_ic_refuse_view_outline,
    'reliz_outline': AdmiralIcons.admiral_ic_reliz_outline,
    'reliz_solid': AdmiralIcons.admiral_ic_reliz_solid,
    'report_outline': AdmiralIcons.admiral_ic_report_outline,
    'report_solid': AdmiralIcons.admiral_ic_report_solid,
    'resize_table_outline': AdmiralIcons.admiral_ic_resize_table_outline,
    'right_double_outline': AdmiralIcons.admiral_ic_right_double_outline,
    'rip_outline': AdmiralIcons.admiral_ic_rip_outline,
    'rip_solid': AdmiralIcons.admiral_ic_rip_solid,
    'robot_outline': AdmiralIcons.admiral_ic_robot_outline,
    'robot_solid': AdmiralIcons.admiral_ic_robot_solid,
    'rotate_left_outline': AdmiralIcons.admiral_ic_rotate_left_outline,
    'rotate_left_solid': AdmiralIcons.admiral_ic_rotate_left_solid,
    'rotate_right_outline': AdmiralIcons.admiral_ic_rotate_right_outline,
    'rotate_right_solid': AdmiralIcons.admiral_ic_rotate_right_solid,
    'row_delete_outline': AdmiralIcons.admiral_ic_row_delete_outline,
    'row_insert_after_outline':
        AdmiralIcons.admiral_ic_row_insert_after_outline,
    'row_insert_below_outline':
        AdmiralIcons.admiral_ic_row_insert_below_outline,
    'rub_outline': AdmiralIcons.admiral_ic_rub_outline,
    'rub_solid': AdmiralIcons.admiral_ic_rub_solid,
    'safety_certificate_outline':
        AdmiralIcons.admiral_ic_safety_certificate_outline,
    'safety_certificate_solid':
        AdmiralIcons.admiral_ic_safety_certificate_solid,
    'safety_outline': AdmiralIcons.admiral_ic_safety_outline,
    'safety_solid': AdmiralIcons.admiral_ic_safety_solid,
    'save_outline': AdmiralIcons.admiral_ic_save_outline,
    'save_solid': AdmiralIcons.admiral_ic_save_solid,
    'scan_and_send_outline': AdmiralIcons.admiral_ic_scan_and_send_outline,
    'scan_and_send_solid': AdmiralIcons.admiral_ic_scan_and_send_solid,
    'scan_doc_outline': AdmiralIcons.admiral_ic_scan_doc_outline,
    'scan_doc_solid': AdmiralIcons.admiral_ic_scan_doc_solid,
    'scan_outline': AdmiralIcons.admiral_ic_scan_outline,
    'scan_redo_outline': AdmiralIcons.admiral_ic_scan_redo_outline,
    'scan_redo_solid': AdmiralIcons.admiral_ic_scan_redo_solid,
    'scan_solid': AdmiralIcons.admiral_ic_scan_solid,
    'scheme_outline': AdmiralIcons.admiral_ic_scheme_outline,
    'scheme_solid': AdmiralIcons.admiral_ic_scheme_solid,
    'search_outline': AdmiralIcons.admiral_ic_search_outline,
    'search_solid': AdmiralIcons.admiral_ic_search_solid,
    'send_sign_outline': AdmiralIcons.admiral_ic_send_sign_outline,
    'send_sign_solid': AdmiralIcons.admiral_ic_send_sign_solid,
    'sent_outline': AdmiralIcons.admiral_ic_sent_outline,
    'service_request_outline': AdmiralIcons.admiral_ic_service_request_outline,
    'service_request_solid': AdmiralIcons.admiral_ic_service_request_solid,
    'settings_outline': AdmiralIcons.admiral_ic_settings_outline,
    'settings_solid': AdmiralIcons.admiral_ic_settings_solid,
    'share_outline': AdmiralIcons.admiral_ic_share_outline,
    'share_solid': AdmiralIcons.admiral_ic_share_solid,
    'sharing_outline': AdmiralIcons.admiral_ic_sharing_outline,
    'sharing_solid': AdmiralIcons.admiral_ic_sharing_solid,
    'shop_cart_outline': AdmiralIcons.admiral_ic_shop_cart_outline,
    'shop_cart_solid': AdmiralIcons.admiral_ic_shop_cart_solid,
    'shopping_bag_outline': AdmiralIcons.admiral_ic_shopping_bag_outline,
    'shopping_bag_solid': AdmiralIcons.admiral_ic_shopping_bag_solid,
    'show_table_outline': AdmiralIcons.admiral_ic_show_table_outline,
    'show_table_solid': AdmiralIcons.admiral_ic_show_table_solid,
    'sign_another_person_outline':
        AdmiralIcons.admiral_ic_sign_another_person_outline,
    'sign_another_person_solid':
        AdmiralIcons.admiral_ic_sign_another_person_solid,
    'sign_in_outline': AdmiralIcons.admiral_ic_sign_in_outline,
    'sign_in_solid': AdmiralIcons.admiral_ic_sign_in_solid,
    'sign_outline': AdmiralIcons.admiral_ic_sign_outline,
    'sign_solid': AdmiralIcons.admiral_ic_sign_solid,
    'signal_outline': AdmiralIcons.admiral_ic_signal_outline,
    'signal_solid': AdmiralIcons.admiral_ic_signal_solid,
    'silver_outline': AdmiralIcons.admiral_ic_silver_outline,
    'silver_solid': AdmiralIcons.admiral_ic_silver_solid,
    'sim_card_outline': AdmiralIcons.admiral_ic_sim_card_outline,
    'sim_card_solid': AdmiralIcons.admiral_ic_sim_card_solid,
    'size_changer_horizontal_outline':
        AdmiralIcons.admiral_ic_size_changer_horizontal_outline,
    'size_changer_vertical_outline':
        AdmiralIcons.admiral_ic_size_changer_vertical_outline,
    'small_arrow_down_outline':
        AdmiralIcons.admiral_ic_small_arrow_down_outline,
    'small_arrow_down_solid': AdmiralIcons.admiral_ic_small_arrow_down_solid,
    'small_arrow_left_outline':
        AdmiralIcons.admiral_ic_small_arrow_left_outline,
    'small_arrow_left_solid': AdmiralIcons.admiral_ic_small_arrow_left_solid,
    'small_arrow_right_outline':
        AdmiralIcons.admiral_ic_small_arrow_right_outline,
    'small_arrow_right_solid': AdmiralIcons.admiral_ic_small_arrow_right_solid,
    'small_arrow_up_outline': AdmiralIcons.admiral_ic_small_arrow_up_outline,
    'small_arrow_up_solid': AdmiralIcons.admiral_ic_small_arrow_up_solid,
    'small_close_outline': AdmiralIcons.admiral_ic_small_close_outline,
    'small_close_solid': AdmiralIcons.admiral_ic_small_close_solid,
    'sort_down_outline': AdmiralIcons.admiral_ic_sort_down_outline,
    'sort_down_solid': AdmiralIcons.admiral_ic_sort_down_solid,
    'sort_outline': AdmiralIcons.admiral_ic_sort_outline,
    'sort_solid': AdmiralIcons.admiral_ic_sort_solid,
    'sort_up_outline': AdmiralIcons.admiral_ic_sort_up_outline,
    'sort_up_solid': AdmiralIcons.admiral_ic_sort_up_solid,
    'source_outline': AdmiralIcons.admiral_ic_source_outline,
    'source_solid': AdmiralIcons.admiral_ic_source_solid,
    'spell_check_outline': AdmiralIcons.admiral_ic_spell_check_outline,
    'star_outline': AdmiralIcons.admiral_ic_star_outline,
    'star_solid': AdmiralIcons.admiral_ic_star_solid,
    'stop_outline': AdmiralIcons.admiral_ic_stop_outline,
    'stop_solid': AdmiralIcons.admiral_ic_stop_solid,
    'store_outline': AdmiralIcons.admiral_ic_store_outline,
    'store_solid': AdmiralIcons.admiral_ic_store_solid,
    'strim_outline': AdmiralIcons.admiral_ic_strim_outline,
    'strim_solid': AdmiralIcons.admiral_ic_strim_solid,
    'structure_outline': AdmiralIcons.admiral_ic_structure_outline,
    'structure_solid': AdmiralIcons.admiral_ic_structure_solid,
    'study_outline': AdmiralIcons.admiral_ic_study_outline,
    'study_solid': AdmiralIcons.admiral_ic_study_solid,
    'subscript_outline': AdmiralIcons.admiral_ic_subscript_outline,
    'superscript_outline': AdmiralIcons.admiral_ic_superscript_outline,
    'switch_pinned_areas_outline':
        AdmiralIcons.admiral_ic_switch_pinned_areas_outline,
    'switch_pinned_areas_solid':
        AdmiralIcons.admiral_ic_switch_pinned_areas_solid,
    'sync_forbid_outline': AdmiralIcons.admiral_ic_sync_forbid_outline,
    'sync_permit_outline': AdmiralIcons.admiral_ic_sync_permit_outline,
    'table_outline': AdmiralIcons.admiral_ic_table_outline,
    'tablet_outline': AdmiralIcons.admiral_ic_tablet_outline,
    'tablet_solid': AdmiralIcons.admiral_ic_tablet_solid,
    'tasks_outline': AdmiralIcons.admiral_ic_tasks_outline,
    'tasks_solid': AdmiralIcons.admiral_ic_tasks_solid,
    'telegramm_outline': AdmiralIcons.admiral_ic_telegramm_outline,
    'telegramm_solid': AdmiralIcons.admiral_ic_telegramm_solid,
    'test_designer_outline': AdmiralIcons.admiral_ic_test_designer_outline,
    'test_designer_solid': AdmiralIcons.admiral_ic_test_designer_solid,
    'test_manager_outline': AdmiralIcons.admiral_ic_test_manager_outline,
    'test_manager_solid': AdmiralIcons.admiral_ic_test_manager_solid,
    'tester_at_outline': AdmiralIcons.admiral_ic_tester_at_outline,
    'tester_at_solid': AdmiralIcons.admiral_ic_tester_at_solid,
    'tester_ht_outline': AdmiralIcons.admiral_ic_tester_ht_outline,
    'tester_ht_solid': AdmiralIcons.admiral_ic_tester_ht_solid,
    'tester_outline': AdmiralIcons.admiral_ic_tester_outline,
    'tester_solid': AdmiralIcons.admiral_ic_tester_solid,
    'text_bold_outline': AdmiralIcons.admiral_ic_text_bold_outline,
    'text_italic_outline': AdmiralIcons.admiral_ic_text_italic_outline,
    'text_underline_outline': AdmiralIcons.admiral_ic_text_underline_outline,
    'third_person_outline': AdmiralIcons.admiral_ic_third_person_outline,
    'third_person_solid': AdmiralIcons.admiral_ic_third_person_solid,
    'thumbs_down_outline': AdmiralIcons.admiral_ic_thumbs_down_outline,
    'thumbs_down_solid': AdmiralIcons.admiral_ic_thumbs_down_solid,
    'thumbs_up_outline': AdmiralIcons.admiral_ic_thumbs_up_outline,
    'thumbs_up_solid': AdmiralIcons.admiral_ic_thumbs_up_solid,
    'time_outline': AdmiralIcons.admiral_ic_time_outline,
    'time_solid': AdmiralIcons.admiral_ic_time_solid,
    'to_customer_outline': AdmiralIcons.admiral_ic_to_customer_outline,
    'to_customer_solid': AdmiralIcons.admiral_ic_to_customer_solid,
    'treasury_outline': AdmiralIcons.admiral_ic_treasury_outline,
    'treasury_solid': AdmiralIcons.admiral_ic_treasury_solid,
    'trees_outline': AdmiralIcons.admiral_ic_trees_outline,
    'trees_solid': AdmiralIcons.admiral_ic_trees_solid,
    'trophy_outline': AdmiralIcons.admiral_ic_trophy_outline,
    'trophy_solid': AdmiralIcons.admiral_ic_trophy_solid,
    'tune_outline': AdmiralIcons.admiral_ic_tune_outline,
    'tune_solid': AdmiralIcons.admiral_ic_tune_solid,
    'txt_color_outline': AdmiralIcons.admiral_ic_txt_color_outline,
    'typography_outline': AdmiralIcons.admiral_ic_typography_outline,
    'typography_solid': AdmiralIcons.admiral_ic_typography_solid,
    'uah_outline': AdmiralIcons.admiral_ic_uah_outline,
    'uah_solid': AdmiralIcons.admiral_ic_uah_solid,
    'undo_outline': AdmiralIcons.admiral_ic_undo_outline,
    'undo_solid': AdmiralIcons.admiral_ic_undo_solid,
    'unlink_outline': AdmiralIcons.admiral_ic_unlink_outline,
    'unlock_outline': AdmiralIcons.admiral_ic_unlock_outline,
    'unlock_solid': AdmiralIcons.admiral_ic_unlock_solid,
    'unsafety_outline': AdmiralIcons.admiral_ic_unsafety_outline,
    'unsafety_solid': AdmiralIcons.admiral_ic_unsafety_solid,
    'unsign_outline': AdmiralIcons.admiral_ic_unsign_outline,
    'unsign_solid': AdmiralIcons.admiral_ic_unsign_solid,
    'unwrap_outline': AdmiralIcons.admiral_ic_unwrap_outline,
    'update_outline': AdmiralIcons.admiral_ic_update_outline,
    'update_solid': AdmiralIcons.admiral_ic_update_solid,
    'upload_outline': AdmiralIcons.admiral_ic_upload_outline,
    'upload_solid': AdmiralIcons.admiral_ic_upload_solid,
    'usb_outline': AdmiralIcons.admiral_ic_usb_outline,
    'usb_solid': AdmiralIcons.admiral_ic_usb_solid,
    'usd_outline': AdmiralIcons.admiral_ic_usd_outline,
    'usd_solid': AdmiralIcons.admiral_ic_usd_solid,
    'user_delete_outline': AdmiralIcons.admiral_ic_user_delete_outline,
    'user_delete_solid': AdmiralIcons.admiral_ic_user_delete_solid,
    'user_role_from_outline': AdmiralIcons.admiral_ic_user_role_from_outline,
    'user_role_from_solid': AdmiralIcons.admiral_ic_user_role_from_solid,
    'user_role_to_outline': AdmiralIcons.admiral_ic_user_role_to_outline,
    'user_role_to_solid': AdmiralIcons.admiral_ic_user_role_to_solid,
    'utensils_outline': AdmiralIcons.admiral_ic_utensils_outline,
    'utensils_solid': AdmiralIcons.admiral_ic_utensils_solid,
    'vacation_outline': AdmiralIcons.admiral_ic_vacation_outline,
    'vacation_solid': AdmiralIcons.admiral_ic_vacation_solid,
    'verify_sign_outline': AdmiralIcons.admiral_ic_verify_sign_outline,
    'verify_sign_solid': AdmiralIcons.admiral_ic_verify_sign_solid,
    'view_history_outline': AdmiralIcons.admiral_ic_view_history_outline,
    'vip_outline': AdmiralIcons.admiral_ic_vip_outline,
    'vip_solid': AdmiralIcons.admiral_ic_vip_solid,
    'vote_outline': AdmiralIcons.admiral_ic_vote_outline,
    'vote_solid': AdmiralIcons.admiral_ic_vote_solid,
    'watcher_outline': AdmiralIcons.admiral_ic_watcher_outline,
    'watcher_solid': AdmiralIcons.admiral_ic_watcher_solid,
    'watcher_test_it_outline': AdmiralIcons.admiral_ic_watcher_test_it_outline,
    'watcher_test_it_solid': AdmiralIcons.admiral_ic_watcher_test_it_solid,
    'web_outline': AdmiralIcons.admiral_ic_web_outline,
    'web_solid': AdmiralIcons.admiral_ic_web_solid,
    'webhook_outline': AdmiralIcons.admiral_ic_webhook_outline,
    'webhook_solid': AdmiralIcons.admiral_ic_webhook_solid,
    'wifi_outline': AdmiralIcons.admiral_ic_wifi_outline,
    'wifi_solid': AdmiralIcons.admiral_ic_wifi_solid,
    'wiki_outline': AdmiralIcons.admiral_ic_wiki_outline,
    'wiki_solid': AdmiralIcons.admiral_ic_wiki_solid,
    'work_outline': AdmiralIcons.admiral_ic_work_outline,
    'work_solid': AdmiralIcons.admiral_ic_work_solid,
    'wrap_outline': AdmiralIcons.admiral_ic_wrap_outline,
    'xls_outline': AdmiralIcons.admiral_ic_xls_outline,
    'xls_solid': AdmiralIcons.admiral_ic_xls_solid,
    'xml_outline': AdmiralIcons.admiral_ic_xml_outline,
    'xml_solid': AdmiralIcons.admiral_ic_xml_solid,
    'zip_outline': AdmiralIcons.admiral_ic_zip_outline,
    'zip_solid': AdmiralIcons.admiral_ic_zip_solid,
    'zoom_in_outline': AdmiralIcons.admiral_ic_zoom_in_outline,
    'zoom_in_solid': AdmiralIcons.admiral_ic_zoom_in_solid,
    'zoom_out_outline': AdmiralIcons.admiral_ic_zoom_out_outline,
    'zoom_out_solid': AdmiralIcons.admiral_ic_zoom_out_solid,
  };
}
