// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVo8cDHRlXU9p4iHptrAyRH7RySR9xPWA',
    appId: '1:792224744111:web:b98637890236f1b1708a5a',
    messagingSenderId: '792224744111',
    projectId: 'admiral-8e09f',
    authDomain: 'admiral-8e09f.firebaseapp.com',
    storageBucket: 'admiral-8e09f.appspot.com',
    measurementId: 'G-WKCBJ5H05F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmV1PjDfkKlaVCNul0XMxcmyL6SfYmh0',
    appId: '1:792224744111:android:eec44e99b3e88ce3708a5a',
    messagingSenderId: '792224744111',
    projectId: 'admiral-8e09f',
    storageBucket: 'admiral-8e09f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzSz-10LC0DyyfgsblOPDqyXq9yPvFf4',
    appId: '1:792224744111:ios:a52fac26e4fe3887708a5a',
    messagingSenderId: '792224744111',
    projectId: 'admiral-8e09f',
    storageBucket: 'admiral-8e09f.appspot.com',
    iosBundleId: 'com.admiralteam.example',
  );
}
