name: Build Flutter App
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
    branches: ['main', 'develop', 'feature/**', 'rc/**']
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted, main]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          architecture: x64
          distribution: 'zulu'
          java-version: '11'
      - run: flutter --version
      - name: Analyze Flutter env
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
#        TODO: fix golden tests
#      - name: Test App
#        run: flutter test
      - name: Build Web App
        run: cd example && flutter build web
      - name: Build iOS App
        run: cd example && flutter build ios --release --no-codesign
      - name: Build Android App & Apk
        run: cd example && flutter build apk && flutter build appbundle